Repository UMC-CUK-8th/WEB, pull requests merged in 2025-03, with the labels that each got.

#1 Title : 2주차미션1_민
  min/min_web/.gitignore
  min/min_web/README.md
  min/min_web/package-lock.json
  min/min_web/package.json
  min/min_web/public/favicon.ico
  min/min_web/public/index.html
  min/min_web/public/logo192.png
  min/min_web/public/logo512.png
  min/min_web/public/manifest.json
  min/min_web/public/robots.txt
  min/min_web/src/App.css
  min/min_web/src/App.test.js
  min/min_web/src/App.tsx
  min/min_web/src/index.css
  min/min_web/src/index.tsx
  min/min_web/src/logo.svg
  min/min_web/src/pages/TodoList/Styles.ts
  min/min_web/src/pages/TodoList/Todo.tsx
  min/min_web/src/pages/TodoList/components/CompletedList.tsx
  min/min_web/src/pages/TodoList/components/TodoInput.tsx
  min/min_web/src/pages/TodoList/components/TodoItem.tsx
  min/min_web/src/pages/TodoList/components/TodoList.tsx
  min/min_web/src/reportWebVitals.ts
  min/min_web/src/setupTests.ts
  min/min_web/tsconfig.json
Labels: bug, invalid, feat

#2 Title : 1주차미션_매디
  todo/dist/script.js
  todo/package-lock.json
  todo/package.json
  todo/src/index.html
  todo/src/script.ts
  todo/src/style.css
  todo/tsconfig.json
Labels: feat

#11 Title : 2주차 미션_고민균
  Min/TodoList/.gitignore
  Min/TodoList/README.md
  Min/TodoList/eslint.config.js
  Min/TodoList/index.html
  Min/TodoList/package-lock.json
  Min/TodoList/package.json
  Min/TodoList/public/vite.svg
  Min/TodoList/src/06-useContext/ContextPage.tsx
  Min/TodoList/src/06-useContext/Navbar.tsx
  Min/TodoList/src/06-useContext/ThemeContent.tsx
  Min/TodoList/src/06-useContext/ThemeToggleButton.tsx
  Min/TodoList/src/06-useContext/context/ThemeProvider.tsx
  Min/TodoList/src/App.css
  Min/TodoList/src/App.tsx
  Min/TodoList/src/assets/react.svg
  Min/TodoList/src/contexts/TodoContext.tsx
  Min/TodoList/src/index.css
  Min/TodoList/src/main.tsx
  Min/TodoList/src/pages/TodoList/Styles.ts
  Min/TodoList/src/pages/TodoList/Todo.tsx
  Min/TodoList/src/pages/TodoList/components/CompletedList.tsx
  Min/TodoList/src/pages/TodoList/components/TodoInput.tsx
  Min/TodoList/src/pages/TodoList/components/TodoItem.tsx
  Min/TodoList/src/pages/TodoList/components/TodoList.tsx
  Min/TodoList/src/vite-env.d.ts
  Min/TodoList/tsconfig.app.json
  Min/TodoList/tsconfig.json
  Min/TodoList/tsconfig.node.json
  Min/TodoList/vite.config.ts
Labels: invalid, feat, style
