Repository UMC-CUK-8th/WEB, pull requests merged in 2025-05, with the labels that each got.

#44 Title : 5주차 미션_민
  UMC-8th-mission-FE/public/images/Back.svg
  UMC-8th-mission-FE/public/images/google.svg
  UMC-8th-mission-FE/src/App.css
  UMC-8th-mission-FE/src/App.tsx
  UMC-8th-mission-FE/src/apis/auth.ts
  UMC-8th-mission-FE/src/apis/axios.ts
  UMC-8th-mission-FE/src/constants/key.ts
  UMC-8th-mission-FE/src/context/AuthContext.tsx
  UMC-8th-mission-FE/src/hooks/useForm.ts
  UMC-8th-mission-FE/src/layouts/HomeLayout.tsx
  UMC-8th-mission-FE/src/layouts/ProtectedLayout.tsx
  UMC-8th-mission-FE/src/pages/GoogleLoginRedirectPage.tsx
  UMC-8th-mission-FE/src/pages/HomePage.tsx
  UMC-8th-mission-FE/src/pages/Loginpage.tsx
  UMC-8th-mission-FE/src/pages/MyPage.tsx
  UMC-8th-mission-FE/src/pages/SignupPage.tsx
Labels: bug, feat

#41 Title: 5주차 미션_매디
  movie-app/src/App.tsx
  movie-app/src/api/auth.ts
  movie-app/src/api/axiosInstance.ts
  movie-app/src/components/navbar.tsx
  movie-app/src/components/protectedRoute.tsx
  movie-app/src/context/authContext.tsx
  movie-app/src/main.tsx
  movie-app/src/pages/login.tsx
  movie-app/src/pages/my.tsx
  movie-app/src/pages/oauthCallback.tsx
  movie-app/src/pages/signup.tsx
  movie-app/src/utils/jwt.ts
Labels: enhancement, feat

#51 Title: 6주차 미션_민
  UMC-8th-mission-FE/package.json
  UMC-8th-mission-FE/pnpm-lock.yaml
  UMC-8th-mission-FE/public/images/Search.svg
  UMC-8th-mission-FE/public/images/editIcon.svg
  UMC-8th-mission-FE/public/images/mypageIcon.svg
  UMC-8th-mission-FE/public/images/trashIcon.svg
  UMC-8th-mission-FE/src/App.tsx
  UMC-8th-mission-FE/src/apis/lp.ts
  UMC-8th-mission-FE/src/components/Button/FloatingAddButton.tsx
  UMC-8th-mission-FE/src/components/Footer.tsx
  UMC-8th-mission-FE/src/components/LpCard/LpCard.tsx
  UMC-8th-mission-FE/src/components/LpCard/LpCardSkeleton.tsx
  UMC-8th-mission-FE/src/components/LpCard/LpCardSkeletonList.tsx
  UMC-8th-mission-FE/src/components/LpDetail/CommentInput.tsx
  UMC-8th-mission-FE/src/components/LpDetail/CommentList.tsx
  UMC-8th-mission-FE/src/components/LpDetail/CommentSkeleton.tsx
  UMC-8th-mission-FE/src/components/LpDetail/CommentSkeletonList.tsx
  UMC-8th-mission-FE/src/components/LpDetail/LpHeader.tsx
  UMC-8th-mission-FE/src/components/LpDetail/LpImagePlayer.tsx
  UMC-8th-mission-FE/src/components/LpDetail/LpLikeButton.tsx
  UMC-8th-mission-FE/src/components/LpDetail/LpTags.tsx
  UMC-8th-mission-FE/src/components/Navbar.tsx
  UMC-8th-mission-FE/src/components/SideBar.tsx
  UMC-8th-mission-FE/src/constants/key.ts
  UMC-8th-mission-FE/src/enums/common.ts
  UMC-8th-mission-FE/src/hooks/queries/useGetInfiniteLpList.tsx
  UMC-8th-mission-FE/src/hooks/queries/useGetLpDetail.tsx
  UMC-8th-mission-FE/src/hooks/queries/useGetLpList.tsx
  UMC-8th-mission-FE/src/hooks/queries/useInfiniteComment.tsx
  UMC-8th-mission-FE/src/layouts/HomeBeforeLayout.tsx
  UMC-8th-mission-FE/src/layouts/HomeLayout.tsx
  UMC-8th-mission-FE/src/layouts/ProtectedLayout.tsx
  UMC-8th-mission-FE/src/pages/HomePage.tsx
  UMC-8th-mission-FE/src/pages/LpDetailPage.tsx
  UMC-8th-mission-FE/src/types/common.ts
  UMC-8th-mission-FE/src/types/lp.ts
Labels: feat, style

#55 Title: 7주차 미션_매디
  movie-app/src/api/comment.ts
  movie-app/src/api/createLP.ts
  movie-app/src/api/like.ts
  movie-app/src/api/postComment.ts
  movie-app/src/api/uploadImage.ts
  movie-app/src/assets/icon/LP.jpeg
  movie-app/src/components/floatingAddButton.tsx
  movie-app/src/components/lpModal.tsx
  movie-app/src/components/navbar.tsx
  movie-app/src/components/sidebar.tsx
  movie-app/src/layout/root-layout.tsx
  movie-app/src/pages/home.tsx
  movie-app/src/pages/login.tsx
  movie-app/src/pages/lpDetail.tsx
  movie-app/src/pages/my.tsx
Labels: enhancement, feat, style

#58 Title: 7주차 과제_민
  UMC-8th-mission-FE/public/images/LpImage.png
  UMC-8th-mission-FE/public/images/jokeBear.png
  UMC-8th-mission-FE/src/App.tsx
  UMC-8th-mission-FE/src/apis/comment.ts
  UMC-8th-mission-FE/src/apis/lp.ts
  UMC-8th-mission-FE/src/apis/my.ts
  UMC-8th-mission-FE/src/components/Button/FloatingAddButton.tsx
  UMC-8th-mission-FE/src/components/LpDetail/CommentChange/CommentDeleteButton.tsx
  UMC-8th-mission-FE/src/components/LpDetail/CommentChange/CommentEditSection.tsx
  UMC-8th-mission-FE/src/components/LpDetail/CommentInput.tsx
  UMC-8th-mission-FE/src/components/LpDetail/CommentList.tsx
  UMC-8th-mission-FE/src/components/LpDetail/LpHeader.tsx
  UMC-8th-mission-FE/src/components/LpDetail/LpLikeButton.tsx
  UMC-8th-mission-FE/src/components/Modal/AddLpModal.tsx
  UMC-8th-mission-FE/src/components/Modal/DeleteModal.tsx
  UMC-8th-mission-FE/src/components/Modal/LpForm.tsx
  UMC-8th-mission-FE/src/components/Modal/TagInput.tsx
  UMC-8th-mission-FE/src/components/SideBar.tsx
  UMC-8th-mission-FE/src/constants/key.ts
  UMC-8th-mission-FE/src/context/AuthContext.tsx
  UMC-8th-mission-FE/src/hooks/mutations/useDeleteCommentMutation.ts
  UMC-8th-mission-FE/src/hooks/mutations/useDeleteLike.ts
  UMC-8th-mission-FE/src/hooks/mutations/useLoginMutation.ts
  UMC-8th-mission-FE/src/hooks/mutations/useLogoutMutation.ts
  UMC-8th-mission-FE/src/hooks/mutations/usePatchCommentMutation.ts
  UMC-8th-mission-FE/src/hooks/mutations/usePostComment.ts
  UMC-8th-mission-FE/src/hooks/mutations/usePostLike.ts
  UMC-8th-mission-FE/src/hooks/mutations/usePostLp.tsx
  UMC-8th-mission-FE/src/hooks/mutations/useUpdateMyInfo.ts
  UMC-8th-mission-FE/src/hooks/queries/useGetInfiniteLpList.ts
  UMC-8th-mission-FE/src/hooks/queries/useGetLpDetail.ts
  UMC-8th-mission-FE/src/hooks/queries/useGetLpList.ts
  UMC-8th-mission-FE/src/hooks/queries/useGetMyInfo.ts
  UMC-8th-mission-FE/src/hooks/queries/useInfiniteComment.ts
  UMC-8th-mission-FE/src/pages/HomePage.tsx
  UMC-8th-mission-FE/src/pages/LpDetailPage.tsx
  UMC-8th-mission-FE/src/pages/LpTestDetailPage.tsx
  UMC-8th-mission-FE/src/pages/MyPage.tsx
  UMC-8th-mission-FE/src/types/lp.ts
Labels: feat, style
